### PR TITLE
Drop support for older versions of Python and Django

### PR DESCRIPTION
**Pull request by moggers87**
This is a major release:

- Drop support for Python 2 and Python 3.4
- Drop support for Django 1.8-2.1
- Add support for Python 3.8 and 3.9
- Add support for Django 3.0 and 3.1
- Removed code that was required to support older versions of Python and Django

### CODE REVIEW

**Comment by moggers87** [comment]
Not exactly sure why coverage thinks that one line is getting no coverage 🤷

**Comment by justinmayer** [comment]
Thanks for working on this, and apologies for the delay on my end. End + beginning of year was a bit hectic. Will have a look soon.

**Comment by moggers87** [comment]
I forgot all about this. Updating my branch with latest Django

**Comment by justinmayer** [comment]
Sincere apologies. Many thanks for reminding me about this. Do you think this would be a good opportunity to add Python 3.9 to the list of supported Python versions?

**Comment by moggers87** [comment]
I don't think Travis has Python 3.9 available yet, though we could test against 3.9-dev.

**Comment by moggers87** [comment]
Added "3.9-dev" as that's all Travis has available right now

**Comment by justinmayer** [comment]
Indeed — perhaps someday in the future we might consider moving CI/CD to GitHub Actions.

**Review by justinmayer — APPROVED** [review]
Everything here looks great. Many thanks for all your work on the Elevate modernization! ✨

**Pull request merged**
